config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }
  root to: "users/products#index"

  namespace :admins do
    resources :products
    resources :users, except: %i[new create]
    resources :orders, only: %i[index show edit update]
    patch "update_display_order_products", to: "site_settings#update_display_order_products", as: "update_products_order"
  end

  scope module: :users do
    resources :products, only: %i[index show]
    resources :cart_items, only: %i[index create destroy] do
      member do
        patch :increment
        patch :decrement
      end
    end
    resource :user, only: %i[show] do
      member do
        get :edit_address
        patch :update_address
      end
    end
    resources :orders do
      member do
        get :confirm
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  enum status: {
    pending: 0,
    confirmed: 1,
    preparing: 2,
    shipped: 3,
    canceled: 99
  }
  STATUS_NAMES = {
    pending: "未確定",
     confirmed: "確定",
     preparing: "準備中",
     shipped: "発送済み",
     canceled: "キャンセル"
  }.freeze

  enum delivery_time_slot: {
    eight_to_twelve: 0,
    twelve_to_two: 1,
    two_to_four: 2,
    four_to_six: 3,
    six_to_eight: 4,
    eight_to_nine: 5,
    not_specified: 99
  }
  DELIVERY_TIME_SLOT_NAMES = {
    eight_to_twelve: "8時〜12時",
    twelve_to_two: "12時〜14時",
    two_to_four: "14時〜16時",
    four_to_six: "16時〜18時",
    six_to_eight: "18時〜20時",
    eight_to_nine: "20時〜21時",
    not_specified: "指定なし"
  }.freeze

  validate :delivery_date_within_business_days
  validates :delivery_time_slot, inclusion: { in: delivery_time_slots.keys, allow_nil: true }

  def num_of_items
    order_items.sum { |order_item| order_item.quantity }
  end

  # 　商品の合計金額（税抜き）
  def sub_total
    order_items.sum { |order_item| order_item.price * order_item.quantity }
  end

  def status_name
    STATUS_NAMES[status.to_sym]
  end

  def delivery_time_slot_name
    DELIVERY_TIME_SLOT_NAMES[delivery_time_slot.to_sym]
  end

  def orderer_full_name
    orderer_last_name + " " + orderer_first_name
  end

  def display_address
    postal_code + " " + address
  end

  def num_of_items
    order_items.sum { |order_item| order_item.quantity }
  end

  private

  def delivery_date_within_business_days
    return if delivery_date.blank?

    unless delivery_date >= 3.business_days.from_now &&
           delivery_date <= 14.business_days.from_now
      errors.add(:delivery_date, "は3営業日から14営業日以内で指定してください。")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save :format_postal_code

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :postal_code, format: { with: /\A\d{3}-?\d{4}\z/, message: "は「123-4567」または「1234567」の形式で入力してください" }

  scope :default_order, -> { order(id: :asc) }

  def address_info_registered?
    last_name.present? && first_name.present? && postal_code.present? && address.present?
  end

  private

  def format_postal_code
    self.postal_code = postal_code.insert(3, "-") if postal_code.present? && postal_code.length == 7
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < Admins::ApplicationController
  before_action :set_order, only: %i[show edit update]
  def index
    @orders = Order.not_pending
  end

  def show
    @order_items = @order.order_items.includes(:product)
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to admins_order_path(@order), notice: "更新しました。"
    else
      redirect_to admins_order_path(@order), alert: "更新できませんでした。"
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:status, :orderer_last_name, :orderer_first_name, :postal_code, :address, :delivery_date, :delivery_time_slot)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :destroy ]

  def index
    @users = User.default_order
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admins_user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @user.destroy
    redirect_to admins_users_path, notice: "ユーザーを削除しました。"
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :postal_code, :address)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/user/products_controller.rb
class User::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users/application_controller.rb
class Users::ApplicationController < ::ApplicationController
  layout "users"
end

app/controllers/users/cart_items_controller.rb
class Users::CartItemsController < Users::ApplicationController
  include Chargeable

  before_action :authenticate_user!

  def index
    set_charge
    @cart_items = current_user.cart_items.includes(product: { image_attachment: :blob })
  end

  def create
    @cart_item = current_user.cart_items.find_by(product_id: params[:product_id])
    if @cart_item
      @cart_item.increment!(:quantity)
    else
      current_user.cart_items.create!(product_id: params[:product_id])
    end
    redirect_to products_path, notice: "カートに商品を追加しました"
  end

  def increment
    current_user.cart_items.find(params[:id]).increment!(:quantity)

    redirect_to cart_items_path
  end

  def decrement
    @cart_item = current_user.cart_items.find(params[:id])

    if @cart_item.quantity <= 1
      @cart_item.destroy
    else
      @cart_item.decrement!(:quantity)
    end

    redirect_to cart_items_path
  end

  def destroy
    @cart_item = current_user.cart_items.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < Users::ApplicationController
  include Chargeable

  before_action :authenticate_user!
  before_action :set_order, only: %i[show edit update destroy]
  before_action :ensure_address_info_registered, only: %i[create]

  def index
    @orders = current_user.orders.not_pending
  end

  def show
  end

  def new
    @order = current_user.orders.build
  end

  def create
    set_charge
    @order = current_user.orders.build(
      total_charge: @total_charge,
      cod_fee: @cod_fee,
      tax_rate: @tax_rate,
      shipping_fee: @shipping_fee,
      status: :pending,
      postal_code: current_user.postal_code,
      address: current_user.address,
      orderer_last_name: current_user.last_name,
      orderer_first_name: current_user.first_name
    )
    @order.assign_attributes(order_params)
    current_user.cart_items.each do |cart_item|
      @order.order_items.build(
        product_id: cart_item.product_id,
        quantity: cart_item.quantity,
        price: cart_item.product.price,
        name: cart_item.product.name
      )
    end
    if @order.save
      redirect_to confirm_order_path(@order)
    else
      render :new, status: :unprocessable_content
    end
  end

  def confirm
    @order = current_user.orders.find(params[:id])
  end

  def edit
  end

  def update
    begin
      ActiveRecord::Base.transaction do
        @order.confirmed!
        @order.update!(confirmed_at: Time.zone.now)
        current_user.cart_items.destroy_all
      end
      redirect_to orders_path, notice: "注文を確定しました。"
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved
      redirect_to confirm_order_path(@order), alert: "注文処理に失敗しました。"
    end
  end

  def destroy
    @order.cancel!
    redirect_to users_orders_path, notice: "注文をキャンセルしました。"
  end

  private
  def set_order
    @order = current_user.orders.find(params[:id])
  end

  def order_params
    params.require(:order).permit(
      :delivery_date,
      :delivery_time_slot
    )
  end

  def ensure_address_info_registered
    unless current_user.address_info_registered?
      session[:return_to] = request.fullpath
      redirect_to edit_address_user_path, alert: "住所を登録してください。"
    end
  end

  private
  def set_new_order
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/products_controller.rb
class Users::ProductsController < Users::ApplicationController
  def index
    display_order = SiteSetting.find_by(key: "display_order_products")&.value
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).with_attached_image.publish.setting_order(display_order)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < Users::ApplicationController
  before_action :authenticate_user!

  def show
    @orders = current_user.orders.not_pending
  end

  def edit_address
  end

  def update_address
    if current_user.update(user_params)
      redirect_to session.delete(:return_to) || user_path, notice: "郵送先が更新されました。"
    else
      render :edit_address, status: :unprocessable_content
    end
  end
  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :postal_code, :address)
  end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/user/products_helper.rb
module User::ProductsHelper
end

app/helpers/users/cart_items_helper.rb
module Users::CartItemsHelper
end

app/views/users/orders/_ordered_history.html.erb
<table class="table">
  <thead>
    <tr>
      <th>購入日</th>
      <th>支払い総額</th>
      <th>購入品</th>
      <th>状態</th>
      <th>詳細</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= number_to_currency(order.total_charge, unit: "¥") %></td>
        <td>
          <ul class="list-unstyled">
            <% order.order_items.each do |order_item| %>
              <li><%= order_item.product.name %></li>
            <% end %>
          </ul>
        </td>
        <td><%= order.status_name %></td>
        <td><%= link_to "詳細を見る", order_path(order.id), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/orders/confirm.html.erb
<div class="container my-5">
  <h1>注文内容確認</h1>
      <div class="list-group">
      <% @order.order_items.each do |order_item| %>
        <div class="list-group-item mb-3 p-3 shadow-sm">
          <div class="row g-5">
            <div class="col-2">
              <%= display_square_image(order_item.product.image)  %>
            </div>

            <div class="col-9">
              <h5 class="mb-3"><%= order_item.name %></h5>
              <p class="mb-2 fw-bold">価格: <%= number_to_currency(order_item.price, unit: "¥") %></p>
              <div class="d-flex mb-3 align-items-center">
                <p class="fw-bold me-3 mb-0">個数: <%= order_item.quantity %></p>
              </div>
              <div class="d-flex justify-content-between">
                <p class="mb-2 fw-bold">合計: <%= number_to_currency(order_item.price * order_item.quantity, unit: "¥") %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>


        <div class="list-group-item mb-3 p-3 shadow-sm">
          <h5>お支払い総額</h5>
          <div class="row">
            <div class="col-3">
              <p class="mb-0">商品の個数: </p>
              <p class="mb-0">小計（商品のみ): </p>

              <br>

              <p class="mb-0">代引き手数料: </p>
              <p class="mb-0">送料: </p>
              <p class="mb-0">消費税率: </p>
            </div>
            <div class="col-3">
              <p class="mb-0 fw-bold"><%= @order.num_of_items %>個</p>
              <p class="mb-0 fw-bold"><%= number_to_currency(@order.sub_total, unit: "¥") %></p>

              <br>

              <p class="mb-0 fw-bold"><%= number_to_currency(@order.cod_fee, unit: "¥") %></p>
              <p class="mb-0 fw-bold"><%= number_to_currency(@order.shipping_fee, unit: "¥") %></p>
              <p class="mb-0 fw-bold"><%= @order.tax_rate*100.to_i %>%</p>
            </div>
          </div>
          <hr class="my-2">
          <div class="row">
            <div class="col-3">
              <p class="mb-0">合計</p>
            </div>
            <div class="col-3">
              <p class="mb-0 fw-bold"><%= number_to_currency(@order.total_charge, unit: "¥") %></p>
            </div>
          </div>
        </div>
        <div class="list-group-item mb-3 p-3 shadow-sm">
          <h5>お届け先</h5>
          <div class="row">
            <div class="col-3">
              <p class="mb-0">性: </p>
              <p class="mb-0">名: </p>
              <p class="mb-0">郵便番号: </p>
              <p class="mb-0">住所: </p>
            </div>
            <div class="col-3">
              <p class="mb-0 fw-bold"><%= @order.orderer_last_name %></p>
              <p class="mb-0 fw-bold"><%= @order.orderer_first_name %></p>
              <p class="mb-0 fw-bold"><%= @order.postal_code %></p>
              <p class="mb-0 fw-bold"><%= @order.address %></p>
            </div>
          </div>
        </div>
        <div class="list-group-item mb-3 p-3 shadow-sm">
          <h5>配送日時の指定</h5>
          <div class="row">
            <div class="col-3">
              <p class="mb-0">配送日</p>
              <p class="mb-0">配送時間</p>
            </div>
            <div class="col-3">
              <p class="mb-0 fw-bold"><%= @order.delivery_date || "指定なし" %></p>
              <p class="mb-0 fw-bold"><%= @order.delivery_time_slot_name %></p>
            </div>
          </div>
        </div>
        <%= link_to "注文を確定する", order_path(@order), data: { turbo_method: :put }, class: "btn btn-primary" %>
      </div>
    </div>
</div>

app/views/users/orders/index.html.erb
<div class="container">
  <h1>注文履歴</h1>
  <div class="row">
    <div class="col-md-12">
      <%= render "users/orders/ordered_history" %>
    </div>
</div>

app/views/users/orders/new.html.erb
<h1>配送日時の指定</h1>

<%= form_with model: @order, class: "p-4 border rounded shadow-sm" do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-danger">
      <ul class="m-0">
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :delivery_date, "配達日", class: "form-label" %>
    <%= f.date_field :delivery_date, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :delivery_time_slot, "配達時間帯", class: "form-label" %><br>
    <div>
      <% Order.delivery_time_slots.keys.each do |key| %>
        <div class="form-check form-check-inline">
          <%= f.radio_button :delivery_time_slot, key, class: "form-check-input" %>
          <%= f.label :delivery_time_slot, Order::DELIVERY_TIME_SLOT_NAMES[key.to_sym], value: key, class: "form-check-label" %>
        </div>
      <% end %>
    </div>
  </div>


  <div class="text-center">
    <%= f.submit "注文内容の確認へ", class: "btn btn-primary" %>
    <p class="mb-0 fw-lighter">※配達日時の指定がない場合は、そのままお進みください。</p>
  </div>
<% end %>