config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }
  root to: "users/products#index"

  namespace :admins do
    resources :products
    resources :users, except: %i[new create]
    resources :orders, only: %i[index show edit update]
    patch "update_display_order_products", to: "site_settings#update_display_order_products", as: "update_products_order"
  end

  scope module: :users do
    resources :products, only: %i[index show]
    resources :cart_items, only: %i[index create destroy] do
      member do
        patch :increment
        patch :decrement
      end
    end
    resource :user, only: %i[show] do
      member do
        get :edit_address
        patch :update_address
      end
    end
    resources :orders do
      member do
        get :confirm
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  enum status: {
    pending: 0,
    confirmed: 1,
    preparing: 2,
    shipped: 3,
    canceled: 99
  }
  STATUS_NAMES = {
    pending: "未確定",
     confirmed: "確定",
     preparing: "準備中",
     shipped: "発送済み",
     canceled: "キャンセル"
  }.freeze

  enum delivery_time_slot: {
    eight_to_twelve: 0,
    twelve_to_two: 1,
    two_to_four: 2,
    four_to_six: 3,
    six_to_eight: 4,
    eight_to_nine: 5,
    not_specified: 99
  }
  DELIVERY_TIME_SLOT_NAMES = {
    eight_to_twelve: "8時〜12時",
    twelve_to_two: "12時〜14時",
    two_to_four: "14時〜16時",
    four_to_six: "16時〜18時",
    six_to_eight: "18時〜20時",
    eight_to_nine: "20時〜21時",
    not_specified: "指定なし"
  }.freeze

  validate :delivery_date_within_business_days
  validates :delivery_time_slot, inclusion: { in: delivery_time_slots.keys, allow_nil: true }

  def num_of_items
    order_items.sum { |order_item| order_item.quantity }
  end

  # 　商品の合計金額（税抜き）
  def sub_total
    order_items.sum { |order_item| order_item.price * order_item.quantity }
  end

  def status_name
    STATUS_NAMES[status.to_sym]
  end

  def delivery_time_slot_name
    DELIVERY_TIME_SLOT_NAMES[delivery_time_slot.to_sym]
  end

  def orderer_full_name
    orderer_last_name + " " + orderer_first_name
  end

  def display_address
    postal_code + " " + address
  end

  def num_of_items
    order_items.sum { |order_item| order_item.quantity }
  end

  private

  def delivery_date_within_business_days
    return if delivery_date.blank?

    unless delivery_date >= 3.business_days.from_now &&
           delivery_date <= 14.business_days.from_now
      errors.add(:delivery_date, "は3営業日から14営業日以内で指定してください。")
    end
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < Admins::ApplicationController
  before_action :set_order, only: %i[show edit update]
  def index
    @orders = Order.not_pending
  end

  def show
    @order_items = @order.order_items.includes(:product)
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to admins_order_path(@order), notice: "更新しました。"
    else
      redirect_to admins_order_path(@order), alert: "更新できませんでした。"
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:status, :orderer_last_name, :orderer_first_name, :postal_code, :address, :delivery_date, :delivery_time_slot)
  end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < Users::ApplicationController
  include Chargeable

  before_action :authenticate_user!
  before_action :set_order, only: %i[show edit update destroy]
  before_action :ensure_address_info_registered, only: %i[create]

  def index
    @orders = current_user.orders.not_pending
  end

  def show
  end

  def new
    @order = current_user.orders.build
  end

  def create
    set_charge
    @order = current_user.orders.build(
      total_charge: @total_charge,
      cod_fee: @cod_fee,
      tax_rate: @tax_rate,
      shipping_fee: @shipping_fee,
      status: :pending,
      postal_code: current_user.postal_code,
      address: current_user.address,
      orderer_last_name: current_user.last_name,
      orderer_first_name: current_user.first_name
    )
    @order.assign_attributes(order_params)
    current_user.cart_items.each do |cart_item|
      @order.order_items.build(
        product_id: cart_item.product_id,
        quantity: cart_item.quantity,
        price: cart_item.product.price,
        name: cart_item.product.name
      )
    end
    if @order.save
      redirect_to confirm_order_path(@order)
    else
      render :new, status: :unprocessable_content
    end
  end

  def confirm
    @order = current_user.orders.find(params[:id])
  end

  def edit
  end

  def update
    begin
      ActiveRecord::Base.transaction do
        @order.confirmed!
        @order.update!(confirmed_at: Time.zone.now)
        current_user.cart_items.destroy_all
      end
      redirect_to orders_path, notice: "注文を確定しました。"
    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved
      redirect_to confirm_order_path(@order), alert: "注文処理に失敗しました。"
    end
  end

  def destroy
    @order.cancel!
    redirect_to users_orders_path, notice: "注文をキャンセルしました。"
  end

  private
  def set_order
    @order = current_user.orders.find(params[:id])
  end

  def order_params
    params.require(:order).permit(
      :delivery_date,
      :delivery_time_slot
    )
  end

  def ensure_address_info_registered
    unless current_user.address_info_registered?
      session[:return_to] = request.fullpath
      redirect_to edit_address_user_path, alert: "住所を登録してください。"
    end
  end

  private
  def set_new_order
  end
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/users/orders_helper.rb
module Users::OrdersHelper
end

app/views/admins/orders/edit.html.erb
<h2>注文編集</h2>

<%= simple_form_for @order, url: admins_order_path(@order), method: :patch do |f| %>
  <%= f.input :status, as: :radio_buttons, collection: Order.statuses.keys.map { |key| [Order::STATUS_NAMES[key.to_sym], key] } %>
  <%= f.input :orderer_last_name %>
  <%= f.input :orderer_first_name %>
  <%= f.input :postal_code %>
  <%= f.input :address %>
  <%= f.input :delivery_date, include_blank: true %>
  <%= f.input :delivery_time_slot, as: :radio_buttons, collection: Order.delivery_time_slots.keys.map { |key| [Order::DELIVERY_TIME_SLOT_NAMES[key.to_sym], key] } %>

  <div class="actions mt-3">
    <%= f.submit "更新", class: "btn btn-primary" %>
    <%= link_to "キャンセル", admins_orders_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/admins/orders/index.html.erb
<div class="container">
  <h1>注文一覧</h1>
  <div class="container mt-4">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">購入者</th>
            <th scope="col">請求額</th>
            <th scope="col">状態</th>
            <th scope="col">配送先</th>
            <th scope="col">配送日指定</th>
            <th scope="col">購入日</th>
            <th scope="col">アクション</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <th scope="row"><%= order.id %></th>
              <td><%= link_to order.orderer_full_name, admins_user_path(order.user) %></td>
              <td><%= number_to_currency(order.total_charge, unit: "¥") %></td>
              <td><%= order.status_name %></td>
              <td><%= order.display_address.truncate(15) %></td>
              <td><%= order.delivery_date&.strftime("%Y/%m/%d") || "なし" %></td>
              <td><%= order.confirmed_at.strftime("%Y/%m/%d %H:%M") %></td>

              <td class="d-flex gap-2">
                <%= link_to "詳細", admins_order_path(order.id), class: "btn btn-outline-primary" %>
                <%= link_to "編集", edit_admins_order_path(order.id), class: "btn btn-primary" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/orders/show.html.erb
<div class="d-flex align-items-center">
  <h1>注文詳細</h1>

  <%= link_to "注文一覧", admins_orders_path, class: "btn btn-outline-primary ms-2" %>
  <%= link_to "編集", edit_admins_order_path(@order), class: "btn btn-primary ms-2" %>

</div>
<div class="list-group">
  <% @order_items.each do |order_item| %>
    <div class="list-group-item mb-3 p-3 shadow-sm">
      <div class="row">
        <div class="col-2">
          <%= display_square_image(order_item.product.image)  %>
        </div>

        <div class="col-9">
          <h5 class="mb-3"><%= order_item.product.name %></h5>
          <p class="mb-2 fw-bold">価格: <%= number_to_currency(order_item.product.price, unit: "¥") %></p>
          <div class="d-flex mb-3 align-items-center">
            <p class="fw-bold me-3 mb-0">個数: </p>
            <span><%= order_item.quantity %></span>
          </div>
          <div class="d-flex justify-content-between">
            <p class="mb-2 fw-bold">合計: <%= number_to_currency(order_item.product.price * order_item.quantity, unit: "¥") %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>


  <div class="list-group-item mb-3 p-3 shadow-sm">
    <h5>お支払い総額</h5>
    <div class="row">
      <div class="col-3">
        <p class="mb-0">商品の個数: </p>
        <p class="mb-0">小計（商品のみ): </p>

        <br>

        <p class="mb-0">代引き手数料: </p>
        <p class="mb-0">送料: </p>
        <p class="mb-0">消費税率: </p>
      </div>
      <div class="col-3">
        <p class="mb-0 fw-bold"><%= @order.num_of_items %>個</p>
        <p class="mb-0 fw-bold"><%= number_to_currency(@order.sub_total, unit: "¥") %></p>

        <br>

        <p class="mb-0 fw-bold"><%= number_to_currency(@order.cod_fee, unit: "¥") %></p>
        <p class="mb-0 fw-bold"><%= number_to_currency(@order.shipping_fee, unit: "¥") %></p>
        <p class="mb-0 fw-bold"><%= @order.tax_rate*100.to_i %>%</p>
      </div>
    </div>
    <hr class="my-2">
    <div class="row">
      <div class="col-3">
        <p class="mb-0">合計</p>
      </div>
      <div class="col-3">
        <p class="mb-0 fw-bold"><%= number_to_currency(@order.total_charge, unit: "¥") %></p>
      </div>
    </div>
  </div>

  <%# 配送日時の指定 %>
  <div class="list-group-item mb-3 p-3 shadow-sm">
    <h5>配送日時の指定</h5>
    <div class="row">
      <div class="col-3">
        <p class="mb-0">配送日</p>
        <p class="mb-0">配送時間</p>
      </div>
      <div class="col-3">
        <p class="mb-0 fw-bold"><%= @order.delivery_date || "指定なし" %></p>
        <p class="mb-0 fw-bold"><%= @order.delivery_time_slot_name %></p>
      </div>
    </div>
</div>