config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }
  root to: "users/products#index"

  namespace :admins do
    resources :products
    resources :users, except: %i[new create]
    resources :orders, only: %i[index show edit update]
    patch "update_display_order_products", to: "site_settings#update_display_order_products", as: "update_products_order"
  end

  scope module: :users do
    resources :products, only: %i[index show]
    resources :cart_items, only: %i[index create destroy] do
      member do
        patch :increment
        patch :decrement
      end
    end
    resource :user, only: %i[show] do
      member do
        get :edit_address
        patch :update_address
      end
    end
    resources :orders do
      member do
        get :confirm
      end
    end
  end
end

app/views/layouts/_admins_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "さくらマーケット管理者画面", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_admin.email %>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "マイページ", root_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, class: "dropdown-item", data: { turbo_method: :delete } %></li>
          </ul>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_admins_sidebar.html.erb
<div class="list-group">
  <%= link_to "商品管理", admins_products_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "ユーザー管理", admins_users_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "注文管理", admins_orders_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "アドミン", admins_products_path, class: "list-group-item list-group-item-action" %>
</div>

app/views/layouts/_users_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "さくらマーケット", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "日記を見る", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "お買い物", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ショッピングカート", cart_items_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", user_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sakura Market" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if Rails.env.development? %>
      <%= render 'shared/development_nav' %>
    <% end %>
    <%= render "layouts/admins_navbar" %>
    <%= render "shared/flash_messages" %>
    <div class="container-xxl mt-4">
      <div class="row">
        <div class="col-md-3">
          <%= render "layouts/admins_sidebar" %>
        </div>
        <div class="col-md-9 mb-5">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sakura Market" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if Rails.env.development? %>
      <%= render 'shared/development_nav' %>
    <% end %>
    <%= render "shared/flash_messages" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sakura Market" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if Rails.env.development? %>
      <%= render 'shared/development_nav' %>
    <% end %>
    <%= render "layouts/users_navbar" %>
    <%= render "shared/flash_messages" %>

    <div class="container my-5">
      <%= yield %>
    </div>
  </body>
</html>